/* Generated by Together */

package util.event;

import agent.behaviour.BehaviourChange;

public class BehaviourChangeEvent extends Event {
    public BehaviourChangeEvent(Object thrower) {
        super(thrower);
    }

    public int getAgent() {
        return agent;
    }

    public void setAgent(int agent) {
        this.agent = agent;
    }

    public String getBehavName() {
        return behavName;
    }

    public void setBehavName(String behavName) {
        this.behavName = behavName;
    }

    public BehaviourChange getChange() {
        return (BehaviourChange) getThrower();
    }

    private int agent;
    private String behavName;

}
