/* Generated by Together */
package util.event;

/**
 *	Interface for listeners. Every class that wants to receive events, should
 * 	implement this interface.
 */
public interface Listener {

    /**
     *	This method is called for every object registered for the type of p0.
     * 	Registering has to be done with EventManager.addListener(...)
     */
    void catchEvent(Event p0);
}
