/* Generated by Together */

package util.event;

import environment.Mail;

public class MsgSentEvent extends Event {
    public MsgSentEvent(Object thrower) {
        super(thrower);
    }

    public Mail getMsg() {
        return msg;
    }

    public void setMsg(Mail msg) {
        this.msg = msg;
    }

    public boolean isQuestion() {
        return msg.getMessage().charAt(7) == '?';
    }

    private Mail msg;
}
